### ISSUE TITLE
Aufgabe 3.3 & 3.4

### ISSUE THREAD

**Issue by HoelShare** [VAIB-FH-SWF/Piggeldi#1]
Hi @piggeldi ,

mir ist aufgefallen, dass du in deiner Commit Message Aufgabe 3.3 & 3.4 erwähnst, jedoch hast du diese Vermutlich vergessen zu adden.

**Comment by piggeldi** [comment]
Ne habe direkt Aufgabe 3.2 und 3.3 übersprungen, weil das echt nur marginale unterschiede sind. Aber ich stimme dir zu, dass naming ist irreführend
